[workspace]
members = ["llama-api-server", "chat-prompts", "endpoints", "llama-core"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
endpoints = { path = "endpoints", version = "^0.7" }
chat-prompts = { path = "chat-prompts", version = "^0.7" }
thiserror = "1"
uuid = { version = "1.4", features = ["v4", "fast-rng", "macro-diagnostics"] }
clap = { version = "4.4.6", features = ["cargo", "derive"] }

[patch.crates-io]
socket2 = { git = "https://github.com/second-state/socket2.git", branch = "v0.5.x" }
reqwest = { git = "https://github.com/second-state/wasi_reqwest.git", branch = "0.11.x" }
hyper = { git = "https://github.com/second-state/wasi_hyper.git", branch = "v0.14.x" }
tokio = { git = "https://github.com/second-state/wasi_tokio.git", branch = "v1.36.x" }
